### ISSUE TITLE
Document readthedocs setup

### ISSUE THREAD

**Issue by lunaryorn** [lunaryorn/sphinxcontrib-emacs#15]

**Comment by Fuco1** [comment]
Hi!

I'm updating smartparens docs and in the process I decided to switch from markdownto rst and put it on readthedocs.io.  Now I can get this extension working locally, but I'm at a loss as to how to make their build process install this.  I suppose this issue is ment to address that.  Could you provide at least some very very simple instructions?  I tried google and their docs but couldn't find anything relevant.

Thanks!

**Comment by lunaryorn** [comment]
@Fuco1 You need to create a `requirements.txt` file that includes this extension (see [ours in Flycheck](https://github.com/flycheck/flycheck/blob/master/doc/requirements.txt), for instance) and set that requirements file in the advanced build settings of your project.

Note though that I don't maintain this extension anymore.  I made a couple of wrong choices when I wrote it first, our current, much simplified, attempt to provide Elisp support lives [in the Flycheck sources](https://github.com/flycheck/flycheck/blob/master/doc/elisp.py).

**Comment by Fuco1** [comment]
Hmm, @jorgenschaefer also has his own sphinx support inside elpy it seems.  Any interest in creating a new (combined) package?

`requirements.txt` helped, now it builds :)

**Comment by jorgenschaefer** [comment]
The sphinx stuff in Elpy is _very_ rudimentary. There's a ticket in Elpy to use lunaryon's version. :-)

**Comment by Fuco1** [comment]
@lunaryorn I'm afraid my python situation is rather similar to yours :D But I'll keep it in mind.

Thanks so far.
